<?php

/**
 * @file
 * Theme hooks and preprocess functions for UniSonges Theme.
 */

use Drupal\Core\Menu\MenuTreeParameters;

/**
 * Implements hook_preprocess_page().
 */
function unisonges_theme_preprocess_page(array &$variables): void {
  $menu_name = 'main';
  $menu_tree = \Drupal::menuTree();
  $parameters = (new MenuTreeParameters())
    ->setMaxDepth(2)
    ->onlyEnabledLinks();

  $tree = $menu_tree->load($menu_name, $parameters);
  $manipulators = [
    ['callable' => 'menu.default_tree_manipulators:checkAccess'],
    ['callable' => 'menu.default_tree_manipulators:generateIndexAndSort'],
  ];
  $tree = $menu_tree->transform($tree, $manipulators);
  $variables['unisonges_main_menu'] = $menu_tree->build($tree);
}

/**
 * Implements hook_theme_suggestions_page_alter().
 *
 * Force the front layout on /accueil even if Drupal doesn't treat it as <front>.
 */
function unisonges_theme_theme_suggestions_page_alter(array &$suggestions, array $variables) {
  $path = \Drupal::service('path.current')->getPath();
  $alias = \Drupal::service('path_alias.manager')->getAliasByPath($path);

  if ($alias === '/accueil') {
    $suggestions[] = 'page__front';
  }
}

